# Numpy

In [2]:
%%timeit
l=[i for i in range(100000)]

1.7 ms ± 38 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
import numpy as np

In [4]:
%%timeit
a=np.arange(100000)

30.4 μs ± 1.01 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
l1=[i for i in range(1000000)]
l2=[i for i in range(1000000,2000000)]
l3=[]
import time
start = time.time()
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])
end = time.time()-start
print(end)

0.08868622779846191


In [3]:
import time
start = time.time()
a1=np.arange(1000000)
a2=np.arange(1000000,2000000)
a3=a1+a2
end = time.time()-start
print(end)

0.0064237117767333984


In [4]:
import sys
l1=[i for i in range(1000000)]
print(sys.getsizeof(l1))

8448728


In [10]:
import numpy as np
a1=np.arange(1000000,dtype=np.int8)
print(sys.getsizeof(a1))

1000112


In [7]:
import numpy as np
a2=np.arange(1000000,dtype=np.int64)
print(sys.getsizeof(a1))

8000112


In [18]:
a=np.array((1,2,3),dtype=float)
print(type(a))  # numpy.nth dimensional array
print(a)
a

<class 'numpy.ndarray'>
[1. 2. 3.]


array([1., 2., 3.])

In [21]:
a=np.array((0,2,'','1'),dtype=bool)
print(a)

[False  True False  True]


In [6]:
np.ndim(p)

3

In [5]:
p=np.array([[[1,2],[3,4]],[[4,5],[6,7]],[[8,9],[10,11]]])
print(p)

[[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [29]:
np.ndim(p)

3

In [9]:
print(p.shape)

(3, 2, 2)


In [31]:
h1=np.array([[[1,3,5],[0,0,0]],[[1,1,1],[2,2,2]],[[5,5,5],[6,6,6]]])

In [32]:
h1.shape

(3, 2, 3)

In [40]:
h1.reshape(-1,0)

ValueError: cannot reshape array of size 18 into shape (0)

In [41]:
h1.reshape(-1)

array([1, 3, 5, 0, 0, 0, 1, 1, 1, 2, 2, 2, 5, 5, 5, 6, 6, 6])

In [42]:
print(h1)

[[[1 3 5]
  [0 0 0]]

 [[1 1 1]
  [2 2 2]]

 [[5 5 5]
  [6 6 6]]]


In [14]:
# WAP to create a user defined array to fetch 6 values and convert it to 3d array
a=[int(input(f"Enter {i+1} element")) for i in range(3)]
b=[int(input(f"Enter {i+4} element")) for i in range(3)]
A=np.array([a,b])
print(A)
A.reshape(3,2,1)

Enter 1 element 1
Enter 2 element 2
Enter 3 element 3
Enter 4 element 4
Enter 5 element 5
Enter 6 element 6


[[1 2 3]
 [4 5 6]]


array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [3]:
k= np.random.randint(10,size=(2,5))
print(k)

[[1 7 8 0 7]
 [8 7 6 8 2]]


In [29]:
lm=np.ones((3,3),dtype=int)
print(lm)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [65]:
lz=np.zeros((3,3),dtype=int)
print(lz)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [74]:
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
a3=np.concatenate((a1,a2))
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [77]:
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [33]:
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
a3=np.concatenate((a1,a2),axis=2)
print(a1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
a1=a1.reshape(2,4)

In [19]:
print(np.split(a1,2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [20]:
A=np.split(a1,2)

In [26]:
A1=A[0]
A2=A[1]
print(A)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [115]:
a9=a1.reshape(-1)

In [50]:
a9=np.array_split(a1,2)
a9=a1.reshape(2,-1)

In [52]:
print(a9)

[[1 2 3 4]
 [5 6 7 8]]


In [118]:
np.shape(a9)

(8, 1)